config/routes.rb
College::Application.routes.draw do
  resources :institutes

  resources :students

  get 'students/query/ask' => 'students#query'
  post 'students/query/get' => 'students#get'

  get 'institutes/:id/list' => 'institutes#list'
  get 'search' => 'institutes#search'
  post 'find' => 'institutes#find'

end

app/models/institute.rb
class Institute < ActiveRecord::Base
  attr_accessible :estd, :name
  has_many :students
  before_update :update_student_extended_id

  protected
    def update_student_extended_id
      if self.name_changed?
        students = get_student_list
        students.each do |student|
          student.extended_id = get_extended_id(student)
          # student.extended_id = params[:name]
          student.save
        end
      end
    end

    def get_student_list
      students = Student.where(institute_id: self.id)
    end

    def get_extended_id(student)
      eid = student.student_id.to_s + "_"
      eid += self.name[0...2] + "_"
      eid += student.institute.id.to_s
      eid
    end
end

app/controllers/institutes_controller.rb
class InstitutesController < ApplicationController
  # GET /institutes
  # GET /institutes.json
  def index
    @institutes = Institute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @institutes }
    end
  end

  # GET /institutes/1
  # GET /institutes/1.json
  def show
    @institute = Institute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @institute }
    end
  end

  # GET /institutes/new
  # GET /institutes/new.json
  def new
    @institute = Institute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @institute }
    end
  end

  # edit contorller
  def edit
    @institute = Institute.find(params[:id])
  end

  # POST /institutes
  # POST /institutes.json
  def create
    @institute = Institute.new(params[:institute])

    respond_to do |format|
      if @institute.save
        format.html { redirect_to @institute, notice: 'Institute was successfully created.' }
        format.json { render json: @institute, status: :created, location: @institute }
      else
        format.html { render action: "new" }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /institutes/1
  # PUT /institutes/1.json
  def update
    @institute = Institute.find(params[:id])

    respond_to do |format|
      if @institute.update_attributes(params[:institute])
        format.html { redirect_to @institute, notice: 'Institute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutes/1
  # DELETE /institutes/1.json
  def destroy
    @institute = Institute.find(params[:id])
    @institute.destroy

    respond_to do |format|
      format.html { redirect_to institutes_url }
      format.json { head :no_content }
    end
  end

  def list
    @institute = Institute.find(params[:id])
    @students = Student.where(institute_id: params[:id])
  end

  def search

  end

  def find
    key = params[:key]
    temp = "%"
    for i in 0...key.size
      temp += key[i].upcase + "%"
    end
    # @institutes = Institute.where(name: params[:key])
    @institutes = Institute.where("name LIKE ?", temp)
    render json: @institutes, status: :created, location: @institute
  end

end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/views/institutes/_form.html.erb
<%= form_for(@institute) do |f| %>
  <% if @institute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institute.errors.count, "error") %> prohibited this institute from being saved:</h2>

      <ul>
      <% @institute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :estd %><br />
    <%= f.text_field :estd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/institutes/edit.html.erb
<h1>Editing institute</h1>

<%= render 'form' %>

<%= link_to 'Show', @institute %> |
<%= link_to 'Back', institutes_path %>

app/views/institutes/index.html.erb
<h1>Listing institutes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Estd</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @institutes.each do |institute| %>
  <tr>
    <td><%= institute.name %></td>
    <td><%= institute.estd %></td>
    <td><%= link_to 'Show', institute %></td>
    <td><%= link_to 'Edit', edit_institute_path(institute) %></td>
    <td><%= link_to 'Destroy', institute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Institute', new_institute_path %>

app/views/institutes/list.html.erb
<h1><%= @institute.name %></h1>
<table>
  <tr>
    <th>Student</th>
    <th>Department</th>
    <th>Year</th>
    <th>Maths</th>
    <th>Physics</th>
    <th>Chemistry</th>
  </tr>
<% @students.each do |student| %>
  <tr>
    <td><%= student.student_id %></td>
    <td><%= student.department %></td>
    <td><%= student.year %></td>
    <td><%= student.maths %></td>
    <td><%= student.physics %></td>
    <td><%= student.chemistry %></td>
  </tr>
<% end %>

app/views/institutes/new.html.erb
<h1>New institute</h1>

<%= render 'form' %>

<%= link_to 'Back', institutes_path %>

app/views/institutes/search.html.erb
<h2>Search for college by name</h2>
<div id="search-container">
</div>

app/views/institutes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @institute.name %>
</p>

<p>
  <b>Estd:</b>
  <%= @institute.estd %>
</p>


<%= link_to 'Edit', edit_institute_path(@institute) %> |
<%= link_to 'Back', institutes_path %>